<template>
  <!-- Chain Games Lotto Information Modal -->

  <div id="lotto-info" class="modal modal-fixed-footer modal-info">
    <div class="modal-content">
      <div class="row">
        <div class="modal-header">
          <h4>{{ $t('Lotto Information') }}</h4>
        </div>

        <div class="col s12 justified info-text">
          <p>
            {{ $t('The Chain Games lotto has been developed to be provably fair through processed by any staking node on the network and validated by every other node on the network as it is accepted by the network.') }}
          </p>

          <p>
            {{ $t('The winner is derived directly from the proof-of-stake hash of the block that pays out the lotto.') }}
            {{ $t('This way, the lotto results are tied directly to the mechanism that is used to secure the blockchain.') }}
            {{ $t('The modulo of the number of entries over the proof-of-stake hash is used to determine the winning entry number to select the winner to receive 80% of the pot, 18% is burned and 2% goes to the OMN’s.') }}</p>

          <p>
            <strong>{{ $t('Number of entrants:') }}</strong>

            <br />

            {{ $t('This number is generated by you, the bettors who buy lotto tickets.') }}
          </p>

          <p>
            <strong>{{ $t('Proof-of-stake hash: 256 bit hash') }}</strong>

            <br />

            {{ $t('This number carries in it all the variables needed to make staking a secure process.') }}
          </p>

          <p>
            <strong>{{ $t('Winning Entry Number')}}</strong>

            <br />

            {{ $t('Proof-of-stake hash % number of entrants') }}
          </p>
        </div>
      </div>
    </div>

    <div class="modal-footer bg-gradient">
      <div class="options">
        <button class="modal-close btn">
          {{ $t('Close') }}
        </button>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'LottoInfoModal'
};
</script>
