// These are the same format locales that momentjs library offers
export const DEFAULT_LANG = 'en';
export const DEFAULT_FORMAT = 'en';

// Translations available for the Wagerr Electron App
export const LANGUAGE_LOCALES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' }  
];

// Format locales offered by moements and Wagerr Electron App
export const FORMAT_LOCALES = 
  [
    { code: 'en', name: 'English (United States)'},
    { code: 'es', name: 'Spanish (Spain)'},
    { code: 'af', name: 'Afrikaans'},
    { code: 'ar-dz', name: 'Arabic (Algeria)'},
    { code: 'ar-kw', name: 'Arabic (Kuwait)'},
    { code: 'ar-ly', name: 'Arabic (Libya)'},
    { code: 'ar-ma', name: 'Arabic (Morocco)'},
    { code: 'ar-sa', name: 'Arabic (Saudi Arabia)'},
    { code: 'ar-tn', name: 'Arabic (Tunisia)'},
    { code: 'ar', name: 'Arabic'},
    { code: 'az', name: 'Azerbaijani'},
    { code: 'be', name: 'Belarusian'},
    { code: 'bg', name: 'Bulgarian'},
    { code: 'bm', name: 'Bambara'},
    { code: 'bn', name: 'Bengali'},
    { code: 'bo', name: 'Tibetan'},
    { code: 'br', name: 'Breton'},
    { code: 'bs', name: 'Bosnian'},
    { code: 'ca', name: 'Catalan'},
    { code: 'cs', name: 'Czech'},
    { code: 'cv', name: 'Chuvash'},
    { code: 'cy', name: 'Welsh'},
    { code: 'da', name: 'Danish'},
    { code: 'de-at', name: 'German (Austria)'},
    { code: 'de-ch', name: 'German (Switzerland)'},
    { code: 'de', name: 'German'},
    { code: 'dv', name: 'Divehi'},
    { code: 'el', name: 'Greek'},
    { code: 'en-au', name: 'English (Australia)'},
    { code: 'en-ca', name: 'English (Canada)'},
    { code: 'en-gb', name: 'English (United Kingdom)'},
    { code: 'en-ie', name: 'English (Ireland)'},
    { code: 'en-nz', name: 'English (New Zealand)'},
    { code: 'eo', name: 'Esperanto'},
    { code: 'es-do', name: 'Spanish (Dominican Republic)'},
    { code: 'es-us', name: 'Spanish (United States)'},
    { code: 'et', name: 'Estonian'},
    { code: 'eu', name: 'Basque'},
    { code: 'fa', name: 'Persian'},
    { code: 'fi', name: 'Finnish'},
    { code: 'fo', name: 'Faroese'},
    { code: 'fr-ca', name: 'French (Canada)'},
    { code: 'fr-ch', name: 'French (Switzerland)'},
    { code: 'fr', name: 'French'},
    { code: 'fy', name: 'Western Frisian'},
    { code: 'gd', name: 'Scottish Gaelic'},
    { code: 'gl', name: 'Galician'},
    { code: 'gom-latn', name: 'gom (Latin)'},
    { code: 'gu', name: 'Gujarati'},
    { code: 'he', name: 'Hebrew'},
    { code: 'hi', name: 'Hindi'},
    { code: 'hr', name: 'Croatian'},
    { code: 'hu', name: 'Hungarian'},
    { code: 'hy-am', name: 'Armenian (Armenia)'},
    { code: 'id', name: 'Indonesian'},
    { code: 'is', name: 'Icelandic'},
    { code: 'it', name: 'Italian'},
    { code: 'ja', name: 'Japanese'},
    { code: 'jv', name: 'Javanese'},
    { code: 'ka', name: 'Georgian'},
    { code: 'kk', name: 'Kazakh'},
    { code: 'km', name: 'Khmer'},
    { code: 'kn', name: 'Kannada'},
    { code: 'ko', name: 'Korean'},
    { code: 'ky', name: 'Kirghiz'},
    { code: 'lb', name: 'Luxembourgish'},
    { code: 'lo', name: 'Lao'},
    { code: 'lt', name: 'Lithuanian'},
    { code: 'lv', name: 'Latvian'},
    { code: 'me', name: 'me'},
    { code: 'mi', name: 'Maori'},
    { code: 'mk', name: 'Macedonian'},
    { code: 'ml', name: 'Malayalam'},
    { code: 'mr', name: 'Marathi'},
    { code: 'ms-my', name: 'Malay (Malaysia)'},
    { code: 'ms', name: 'Malay'},
    { code: 'mt', name: 'Maltese'},
    { code: 'my', name: 'Burmese'},
    { code: 'nb', name: 'Norwegian Bokmål'},
    { code: 'ne', name: 'Nepali'},
    { code: 'nl-be', name: 'Dutch (Belgium)'},
    { code: 'nl', name: 'Dutch'},
    { code: 'nn', name: 'Norwegian Nynorsk'},
    { code: 'pa-in', name: 'Punjabi (India)'},
    { code: 'pl', name: 'Polish'},
    { code: 'pt-br', name: 'Portuguese (Brazil)'},
    { code: 'pt', name: 'Portuguese'},
    { code: 'ro', name: 'Romanian'},
    { code: 'ru', name: 'Russian'},
    { code: 'sd', name: 'Sindhi'},
    { code: 'se', name: 'Northern Sami'},
    { code: 'si', name: 'Sinhala'},
    { code: 'sk', name: 'Slovak'},
    { code: 'sl', name: 'Slovenian'},
    { code: 'sq', name: 'Albanian'},
    { code: 'sr-cyrl', name: 'Serbian (Cyrillic)'},
    { code: 'sr', name: 'Serbian'},
    { code: 'ss', name: 'Swati'},
    { code: 'sv', name: 'Swedish'},
    { code: 'sw', name: 'Swahili'},
    { code: 'ta', name: 'Tamil'},
    { code: 'te', name: 'Telugu'},
    { code: 'tet', name: 'Tetum'},
    { code: 'th', name: 'Thai'},
    { code: 'tl-ph', name: 'Tagalog (Philippines)'},
    { code: 'tlh', name: 'Klingon'},
    { code: 'tr', name: 'Turkish'},
    { code: 'tzl', name: 'tzl'},
    { code: 'tzm-latn', name: 'tzm (Latin)'},
    { code: 'tzm', name: 'tzm'},
    { code: 'uk', name: 'Ukrainian'},
    { code: 'ur', name: 'Urdu'},
    { code: 'uz-latn', name: 'Uzbek (Latin)'},
    { code: 'uz', name: 'Uzbek'},
    { code: 'vi', name: 'Vietnamese'},
    { code: 'x-pseudo', name: 'x-pseudo'},
    { code: 'yo', name: 'Yoruba'},
    { code: 'zh-cn', name: 'Chinese (China)'},
    { code: 'zh-hk', name: 'Chinese (Hong Kong SAR China)'},
    { code: 'zh-tw', name: 'Chinese (Taiwan))'}
  ];
