name: wagerr-electron-app
version: 'v2.0.0'

summary:   wagerr, digital currency for decentralized betting
description: |
  Wagerr is a decentralized sportsbook that changes
  the way the world bets on sports.
  
  - built for everyone.
    Wagerr uses distributed blockchain technology to
    execute betting contracts. It escrows,  stakes,
    verifies results, and pays out winners. By eliminating
    centralauthorities, Wagerr solves the most pernicious problems in
    the industry. Reducing corruption and risk results in predictable
    operation. You can bet on Wagerr.
    - Free of All regulatory bodies
    - Unrestricted global Access
    - Support for all major sport leagues
    - Truly Deflationary Chain
  - Value Coupling
    Nearly half of all fees are systematically destroyed — and
    destroying fees diminishes coin supply. It’s a simple matter of
  - supply and demand
    Given steady demand, free markets tend to respond to a dwindling
    supply with rising asset price. Holders of the asset will only
    sell it for the highest price the market will bear. Watch the
    video and check out the “economics” tab for more details on how
    the Wagerr economy works.
  
  Homepage: https://wagerr.com/
  Blockexplorer (main): https://explorer.wagerr.com/
  Blockexplorer (testnet): https://explorer2.wagerr.com/
  Github: https://github.com/wagerr/wagerr/
  Wiki: https://github.com/wagerr/wagerr/wiki
  
  Coinmarketcap: https://coinmarketcap.com/currencies/wagerr/
  
  Chat with us:
  - Discord (https://discord.gg/vvvvDbv)
  
  Social networks/forums:
  - Telegram (https://t.me/wagerrcoin)
  - twitter (https://twitter.com/wagerrx)
  - reddit (https://www.reddit.com/r/Wagerr/)
  - bitcointalk (https://bitcointalk.org/index.php?topic=1911583.0)
  - facebook (https://www.facebook.com/wagerr/)

confinement: strict
grade: stable
base: core18

apps:
  daemon:
    command: app/resources/bin/wagerrd
    plugs: [network, network-bind, home, removable-media]
    #desktop: wagerrd.desktop
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  daemon-testnet:
    command: app/resources/bin/wagerrd --testnet
    plugs: [network, network-bind, home, removable-media]
    #desktop: wagerrd_testnet.desktop
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  daemon-regtest:
    command: app/resources/bin/wagerrd --regtest
    plugs: [network, network-bind, home, removable-media]
    #desktop: wagerrd_regtest.desktop
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  qt:
    command: app/resources/bin/wagerr-qt
    plugs: [network, network-bind,  unity7, desktop, desktop-legacy, wayland, x11, opengl, home, gsettings, screen-inhibit-control, audio-playback, system-observe, browser-support, hardware-observe ]
    desktop: wagerr-qt.desktop
    environment:
      QT_XKB_CONFIG_ROOT: $SNAP_USER_DATA:$SNAP/usr/share:$QT_XKB_CONFIG_ROOT
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib"
  qt-testnet:
    command: app/resources/bin/wagerr-qt --testnet
    plugs: [network, network-bind,  unity7, desktop, desktop-legacy, wayland, x11, opengl, home, gsettings, screen-inhibit-control, audio-playback, system-observe, browser-support, hardware-observe ]
    desktop: wagerr-qt_testnet.desktop
    environment:
      QT_XKB_CONFIG_ROOT: $SNAP_USER_DATA:$SNAP/usr/share:$QT_XKB_CONFIG_ROOT
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  qt-regtest:
    command: app/resources/bin/wagerr-qt --regtest
    plugs: [network, network-bind,  unity7, desktop, desktop-legacy, wayland, x11, opengl, home, gsettings, screen-inhibit-control, audio-playback, system-observe, browser-support, hardware-observe ]
    desktop: wagerr-qt_regtest.desktop
    environment:
      QT_XKB_CONFIG_ROOT: $SNAP_USER_DATA:$SNAP/usr/share:$QT_XKB_CONFIG_ROOT
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  electron:
    command: app/wagerr-electron-app --no-sandbox
    plugs: [network, network-bind,  unity7, desktop, desktop-legacy, wayland, x11, opengl, home, gsettings, screen-inhibit-control, audio-playback, system-observe, browser-support, hardware-observe ]
    desktop: wagerr-electron-app.desktop
    environment:
      QT_XKB_CONFIG_ROOT: $SNAP_USER_DATA:$SNAP/usr/share:$QT_XKB_CONFIG_ROOT
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib"
  electron-testnet:
    command: app/wagerr-electron-app --no-sandbox
    plugs: [network, network-bind,  unity7, desktop, desktop-legacy, wayland, x11, opengl, home, gsettings, screen-inhibit-control, audio-playback, system-observe, browser-support, hardware-observe ]
    desktop: wagerr-electron-app_testnet.desktop
    environment:
      QT_XKB_CONFIG_ROOT: $SNAP_USER_DATA:$SNAP/usr/share:$QT_XKB_CONFIG_ROOT
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib"
  electron-regtest:
    command: app/wagerr-electron-app --no-sandbox
    plugs: [network, network-bind,  unity7, desktop, desktop-legacy, wayland, x11, opengl, home, gsettings, screen-inhibit-control, audio-playback, system-observe, browser-support, hardware-observe ]
    desktop: wagerr-electron-app_regtest.desktop
    environment:
      QT_XKB_CONFIG_ROOT: $SNAP_USER_DATA:$SNAP/usr/share:$QT_XKB_CONFIG_ROOT
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
      LD_LIBRARY_PATH: "$LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri:$SNAP/usr/lib"
  cli:
    command: app/resources/bin/wagerr-cli
    plugs: [network, network-bind, home, removable-media]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  cli-testnet:
    command: app/resources/bin/wagerr-cli --testnet
    plugs: [network, network-bind, home, removable-media]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  cli-regtest:
    command: app/resources/bin/wagerr-cli --regtest
    plugs: [network, network-bind, home, removable-media]
    environment:
      XDG_DATA_DIRS: $SNAP_USER_DATA:$SNAP/usr/share:$XDG_DATA_DIRS
  tx:
    command: app/resources/bin/wagerr-tx
    plugs: [home]
  test:
    command: app/resources/bin/test_wagerr
    plugs: [home]
#  testqt:
#    command: app/resources/bin/test_wagerr-qt
#    plugs: [home]

layout:
  /usr/lib/dri:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri

parts:
  wagerr-electron-app:
    source: http://github.com/wagerr/wagerr-electron-app.git
    source-type: git
    source-tag: v2.0.0
    plugin: nil

    override-build: |
      git apply ${SNAPCRAFT_PROJECT_DIR}/snap/local/patches/X005-update.patch
      wget https://deb.nodesource.com/setup_15.x
      bash ./setup_15.x
      apt -y install nodejs
      HOST="${SNAPCRAFT_ARCH_TRIPLET}"
      wget https://github.com/wagerr/wagerr/releases/download/v4.0.0/wagerr-4.0.0-${HOST}.tar.gz
      tar -xf wagerr-4.0.0-${HOST}.tar.gz
      mkdir bin
      cp -p wagerr-4.0.0/bin/* ./bin
      rm -rf wagerr-4.0.0*
      # build using npm
      npm install
      npm run package
      mkdir $SNAPCRAFT_PART_INSTALL/app
      cd release
      HOSTSHORT=$(echo ${SNAPCRAFT_ARCH_TRIPLET} | awk -F  "-" '{print $1}')
      case ${HOSTSHORT} in
        x86_64)   APPIMAGE=$(find *${HOSTSHORT}*.AppImage);;
        arm)      APPIMAGE=$(find *armv7l*.AppImage);;
        aarch64)  APPIMAGE=$(find *arm64*.AppImage);;
        *)        echo "${HOST} unsupported";
      esac
      chmod a+x $APPIMAGE
      ./$APPIMAGE --appimage-extract
      mv ./squashfs-root/* $SNAPCRAFT_PART_INSTALL/app
      find $SNAPCRAFT_PART_INSTALL/app/ -type d -exec chmod 755 {} \;
      $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders > $SNAPCRAFT_PART_INSTALL/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/gdk-pixbuf-2.0/2.10.0/loaders.cache

    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - locales-all
      - qtwayland5
      - ca-certificates
      - libnss3
      - libgtk-3-0
      - libxtst6
      - libxss1
      - libasound2
      - libglu1-mesa
      - libdbus-glib-1-2
      - libdbusmenu-gtk4
      - libdbusmenu-glib4
      - libgtk2.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libgtk-3-dev
      - libgtk2.0-dev
      - libgdk-pixbuf2.0-dev

    build-packages:
      - curl
      - wget
      - gcc
      - gcc-8
      - g++
      - g++-8
      - git
      - make
      - autoconf
      - automake
      - cmake
      - pkg-config
      - libtool
      - bsdmainutils
      - binutils
      - python3
      - help2man
      - doxygen
      - libgtk-3-dev
      - libgtk2.0-dev
      - libgdk-pixbuf2.0-dev

  desktop:
    source: snap/local/desktop
    plugin: dump

